using System;
using System.Collections.Generic;
using Mapperion.Internal;

namespace Mapperion.Model
{
    /// <summary>
    /// The complete description of how one source type is mapped to one destination type.
    /// Instances are immutable once the configuration is built.
    /// </summary>
    public sealed class TypeMapDefinition
    {
        private static readonly MemberDefinition[] NoMembers = Array.Empty<MemberDefinition>();
        private static readonly ConstructorParameterDefinition[] NoParameters = Array.Empty<ConstructorParameterDefinition>();
        private static readonly TypeMapKey[] NoKeys = Array.Empty<TypeMapKey>();
        private static readonly object[] NoActions = Array.Empty<object>();

        /// <summary>Creates a definition for the given type pair.</summary>
        /// <param name="key">The source and destination types.</param>
        public TypeMapDefinition(TypeMapKey key)
        {
            Key = key;
        }

        /// <summary>Gets the type pair this definition describes.</summary>
        public TypeMapKey Key { get; }

        /// <summary>Gets the source type.</summary>
        public Type SourceType => Key.SourceType;

        /// <summary>Gets the destination type.</summary>
        public Type DestinationType => Key.DestinationType;

        /// <summary>Gets the destination members, in the order they were declared.</summary>
        public IReadOnlyList<MemberDefinition> Members { get; init; } = NoMembers;

        /// <summary>Gets the destination constructor parameters, when the destination is built through one.</summary>
        public IReadOnlyList<ConstructorParameterDefinition> ConstructorParameters { get; init; } = NoParameters;

        /// <summary>
        /// Gets the converter that replaces member-by-member mapping for this pair entirely.
        /// When set, every member definition is ignored.
        /// </summary>
        public Type? TypeConverterType { get; init; }

        /// <summary>Gets the factory used to construct the destination, held as <see cref="object"/>.</summary>
        public object? ConstructUsing { get; init; }

        /// <summary>Gets the actions run before the members are assigned.</summary>
        public IReadOnlyList<object> BeforeMapActions { get; init; } = NoActions;

        /// <summary>Gets the actions run after the members are assigned.</summary>
        public IReadOnlyList<object> AfterMapActions { get; init; } = NoActions;

        /// <summary>Gets the recursion limit for this map, or <see langword="null"/> for no limit.</summary>
        public int? MaxDepth { get; init; }

        /// <summary>Gets a value indicating whether repeated references are tracked so cycles terminate.</summary>
        public bool PreserveReferences { get; init; }

        /// <summary>Gets which side must be fully covered for this map to validate.</summary>
        public MemberListValidation MemberListValidation { get; init; } = MemberListValidation.Destination;

        /// <summary>Gets the maps for derived type pairs handled polymorphically by this one.</summary>
        public IReadOnlyList<TypeMapKey> DerivedMaps { get; init; } = NoKeys;

        /// <summary>Gets the base type pairs whose configuration this map inherits.</summary>
        public IReadOnlyList<TypeMapKey> BaseMaps { get; init; } = NoKeys;

        /// <summary>Gets a value indicating whether this map was generated by reversing another one.</summary>
        public bool IsReverse { get; init; }

        /// <summary>
        /// Gets a value indicating whether this definition replaces member mapping with a converter,
        /// in which case the compiler emits a single call instead of member assignments.
        /// </summary>
        public bool HasTypeConverter => TypeConverterType is not null;

        /// <summary>Finds the definition for a destination member by name.</summary>
        /// <param name="memberName">The destination member name, compared with exact casing.</param>
        /// <returns>The definition, or <see langword="null"/> when the member is not configured.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="memberName"/> is <see langword="null"/>.</exception>
        public MemberDefinition? FindMember(string memberName)
        {
            Guard.NotNull(memberName, nameof(memberName));

            for (int i = 0; i < Members.Count; i++)
            {
                if (string.Equals(Members[i].DestinationMember.Name, memberName, StringComparison.Ordinal))
                {
                    return Members[i];
                }
            }

            return null;
        }

        internal TypeMapDefinition WithMembers(IReadOnlyList<MemberDefinition> members)
        {
            return new TypeMapDefinition(Key)
            {
                Members = members,
                ConstructorParameters = ConstructorParameters,
                TypeConverterType = TypeConverterType,
                ConstructUsing = ConstructUsing,
                BeforeMapActions = BeforeMapActions,
                AfterMapActions = AfterMapActions,
                MaxDepth = MaxDepth,
                PreserveReferences = PreserveReferences,
                MemberListValidation = MemberListValidation,
                DerivedMaps = DerivedMaps,
                BaseMaps = BaseMaps,
                IsReverse = IsReverse,
            };
        }

        /// <inheritdoc />
        public override string ToString() => Key.ToString();
    }
}
