using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Mapperion.SourceGeneration
{
    /// <summary>
    /// Turns the mapping methods of one class into C#.
    /// </summary>
    internal sealed class MapperEmitter
    {
        private readonly SourceProductionContext context;
        private readonly Compilation compilation;
        private readonly List<MethodPlan> plans;
        private readonly Dictionary<string, EnumConverter> converters =
            new Dictionary<string, EnumConverter>(StringComparer.Ordinal);

        internal MapperEmitter(SourceProductionContext context, Compilation compilation, List<MethodPlan> plans)
        {
            this.context = context;
            this.compilation = compilation;
            this.plans = plans;
        }

        internal string Write(INamedTypeSymbol mapper)
        {
            var text = new StringBuilder();
            text.AppendLine("// <auto-generated/>");
            text.AppendLine("#nullable enable");
            text.AppendLine();

            bool namespaced = !mapper.ContainingNamespace.IsGlobalNamespace;

            if (namespaced)
            {
                text.Append("namespace ").AppendLine(mapper.ContainingNamespace.ToDisplayString());
                text.AppendLine("{");
            }

            string indent = namespaced ? "    " : string.Empty;

            text.Append(indent).Append("partial class ").AppendLine(mapper.Name);
            text.Append(indent).AppendLine("{");

            var methods = new StringBuilder();

            foreach (MethodPlan plan in plans)
            {
                WriteMethod(methods, plan, indent + "    ");
            }

            text.Append(methods);

            // Written last because they are discovered while the methods above are written.
            foreach (EnumConverter converter in converters.Values)
            {
                converter.Write(text, indent + "    ");
            }

            text.Append(indent).AppendLine("}");

            if (namespaced)
            {
                text.AppendLine("}");
            }

            return text.ToString();
        }

        private void WriteMethod(StringBuilder text, MethodPlan plan, string indent)
        {
            string parameter = plan.Method.Parameters[0].Name;

            text.Append(indent)
                .Append(Accessibility(plan.Method))
                .Append(" partial ")
                .Append(TypeFacts.Display(plan.DestinationType))
                .Append(' ')
                .Append(plan.Method.Name)
                .Append('(')
                .Append(TypeFacts.Display(plan.SourceType))
                .Append(' ')
                .Append(parameter)
                .AppendLine(")");

            text.Append(indent).AppendLine("{");

            if (TypeFacts.CanBeNull(plan.SourceType))
            {
                text.Append(indent).Append("    if (").Append(parameter).AppendLine(" is null)");
                text.Append(indent).AppendLine("    {");
                text.Append(indent).AppendLine("        return default!;");
                text.Append(indent).AppendLine("    }");
                text.AppendLine();
            }

            string body = BuildInstance(plan, parameter) ?? "default!";

            text.Append(indent).Append("    return ").Append(body).AppendLine(";");
            text.Append(indent).AppendLine("}");
            text.AppendLine();
        }

        private static string Accessibility(IMethodSymbol method)
        {
            switch (method.DeclaredAccessibility)
            {
                case Microsoft.CodeAnalysis.Accessibility.Public:
                    return "public";

                case Microsoft.CodeAnalysis.Accessibility.Internal:
                    return "internal";

                case Microsoft.CodeAnalysis.Accessibility.Protected:
                    return "protected";

                default:
                    return "private";
            }
        }

        private string? BuildInstance(MethodPlan plan, string parameter)
        {
            // An enum is not built, it is converted, and a map straight to one is a map the
            // run-time engine takes without comment.
            if (plan.DestinationType.TypeKind == TypeKind.Enum)
            {
                return Convert(plan, parameter, plan.SourceType, plan.DestinationType, plan.Method.Name);
            }

            ITypeSymbol? element = TypeFacts.ElementOf(plan.SourceType);
            string? materialiser = TypeFacts.Materialiser(plan.DestinationType);

            if (element is not null && materialiser is not null)
            {
                return Sequence(plan, parameter, element, materialiser, "(element)");
            }

            if (plan.DestinationType is not INamedTypeSymbol destination)
            {
                Report(GeneratorDiagnostics.CannotConstruct, plan);
                return null;
            }

            var assigned = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            string creation;

            if (TypeFacts.Parameterless(destination) is not null)
            {
                creation = "new " + TypeFacts.Bare(destination) + "()";
            }
            else
            {
                IMethodSymbol? constructor = TypeFacts.SoleConstructor(destination);

                if (constructor is null)
                {
                    Report(GeneratorDiagnostics.CannotConstruct, plan);
                    return null;
                }

                var arguments = new List<string>();

                foreach (IParameterSymbol argument in constructor.Parameters)
                {
                    string? value = Resolve(plan, parameter, argument.Name, argument.Type);

                    if (value is null)
                    {
                        return null;
                    }

                    arguments.Add(value);
                    assigned.Add(argument.Name);
                }

                creation = "new " + TypeFacts.Bare(destination) + "(" + string.Join(", ", arguments) + ")";
            }

            var initialisers = new List<string>();

            foreach (IPropertySymbol member in TypeFacts.Writable(destination))
            {
                if (assigned.Contains(member.Name))
                {
                    continue;
                }

                if (plan.Ignored.Contains(member.Name))
                {
                    continue;
                }

                string? value = Resolve(plan, parameter, member.Name, member.Type);

                if (value is null)
                {
                    return null;
                }

                initialisers.Add(member.Name + " = " + value);
            }

            return initialisers.Count == 0
                ? creation
                : creation + " { " + string.Join(", ", initialisers) + " }";
        }

        private string? Sequence(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceElement,
            string materialiser,
            string destinationName)
        {
            ITypeSymbol destinationElement = TypeFacts.ElementOf(plan.DestinationType) ?? sourceElement;
            return Sequence(plan, expression, sourceElement, destinationElement, materialiser, destinationName);
        }

        private string? Sequence(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceElement,
            ITypeSymbol destinationElement,
            string materialiser,
            string destinationName)
        {
            string projected = expression;

            if (!TypeFacts.Same(sourceElement, destinationElement))
            {
                MethodPlan? element = Lookup(sourceElement, destinationElement);

                if (element is null)
                {
                    Report(
                        GeneratorDiagnostics.NoConversion,
                        plan,
                        destinationName,
                        TypeFacts.Display(sourceElement),
                        TypeFacts.Display(destinationElement));

                    return null;
                }

                projected = "global::System.Linq.Enumerable.Select(" + expression + ", " + element.Method.Name + ")";
            }

            return "global::System.Linq.Enumerable." + materialiser + "(" + projected + ")";
        }

        private string? Resolve(MethodPlan plan, string parameter, string destinationName, ITypeSymbol destinationType)
        {
            if (plan.Ignored.Contains(destinationName))
            {
                return "default(" + TypeFacts.Bare(destinationType) + ")!";
            }

            if (plan.ExplicitSources.TryGetValue(destinationName, out string? path))
            {
                PathRead? read = ReadPath(plan, parameter, path);

                return read is null
                    ? null
                    : Convert(plan, read.Expression, read.Type, destinationType, destinationName);
            }

            IPropertySymbol? match = Match(plan.SourceType, destinationName);

            if (match is null)
            {
                Report(GeneratorDiagnostics.UnmappedMember, plan, destinationName);
                return null;
            }

            return Convert(plan, parameter + "." + match.Name, match.Type, destinationType, destinationName);
        }

        private static IPropertySymbol? Match(ITypeSymbol sourceType, string name)
        {
            List<IPropertySymbol> readable = TypeFacts.Readable(sourceType);

            foreach (IPropertySymbol property in readable)
            {
                if (string.Equals(property.Name, name, StringComparison.Ordinal))
                {
                    return property;
                }
            }

            foreach (IPropertySymbol property in readable)
            {
                if (string.Equals(property.Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    return property;
                }
            }

            return null;
        }

        /// <remarks>
        /// A path guards every step that could be null, so a missing link in the chain yields the
        /// default rather than throwing. The guards re-read the intermediate members, which the run
        /// time compiler avoids by binding locals; here the readable shape of the generated code is
        /// worth more than saving a property read.
        /// </remarks>
        private PathRead? ReadPath(MethodPlan plan, string parameter, string path)
        {
            ITypeSymbol current = plan.SourceType;
            string expression = parameter;
            var guards = new List<string>();

            string[] steps = path.Split('.');

            for (int i = 0; i < steps.Length; i++)
            {
                IPropertySymbol? property = Match(current, steps[i]);

                if (property is null)
                {
                    Report(GeneratorDiagnostics.UnknownMember, plan, path, TypeFacts.Display(plan.SourceType));
                    return null;
                }

                if (i > 0 && TypeFacts.CanBeNull(current))
                {
                    guards.Add(expression + " is not null");
                }

                expression += "." + property.Name;
                current = property.Type;
            }

            if (guards.Count == 0)
            {
                return new PathRead(expression, current);
            }

            string guarded = "(" + string.Join(" && ", guards) + " ? " + expression +
                " : default(" + TypeFacts.Bare(current) + ")!)";

            return new PathRead(guarded, current);
        }

        private string? Convert(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceType,
            ITypeSymbol destinationType,
            string destinationName)
        {
            if (TypeFacts.Same(sourceType, destinationType))
            {
                return expression;
            }

            ITypeSymbol? sourceElement = TypeFacts.ElementOf(sourceType);
            string? materialiser = TypeFacts.Materialiser(destinationType);

            if (sourceElement is not null && materialiser is not null)
            {
                ITypeSymbol? destinationElement = TypeFacts.ElementOf(destinationType);

                if (destinationElement is not null)
                {
                    return Sequence(plan, expression, sourceElement, destinationElement, materialiser, destinationName);
                }
            }

            string? lifted = Lift(plan, expression, sourceType, destinationType, destinationName);

            if (lifted is not null)
            {
                return lifted;
            }

            Conversion conversion = ((CSharpCompilation)compilation).ClassifyConversion(sourceType, destinationType);

            if (conversion.Exists && conversion.IsImplicit)
            {
                return expression;
            }

            // Before the declared maps, which is where the run-time engine looks at them too. A
            // pair of enums is a conversion and not a map, and putting it the other way round
            // makes a method declared for that pair call itself.
            string? asEnum = TryEnum(expression, sourceType, destinationType);

            if (asEnum is not null)
            {
                return asEnum;
            }

            if (conversion.Exists && (conversion.IsNumeric || conversion.IsEnumeration))
            {
                return "(" + TypeFacts.Bare(destinationType) + ")" + expression;
            }

            if (destinationType.SpecialType == SpecialType.System_String)
            {
                return TypeFacts.CanBeNull(sourceType)
                    ? expression + "?.ToString()"
                    : expression + ".ToString()";
            }

            MethodPlan? mapping = Lookup(sourceType, destinationType);

            if (mapping is not null)
            {
                return mapping.Method.Name + "(" + expression + ")";
            }

            Report(
                GeneratorDiagnostics.NoConversion,
                plan,
                destinationName,
                TypeFacts.Display(sourceType),
                TypeFacts.Display(destinationType));

            return null;
        }

        /// <summary>
        /// Lifts a conversion over a nullable on either side.
        /// </summary>
        /// <remarks>
        /// The run-time engine settles this before it looks at anything else about the pair, so an
        /// absent value gives the destination's default instead of reaching a conversion that
        /// would throw on it. Answering it in the same place is what keeps the two engines saying
        /// the same thing about a value that is not there.
        /// </remarks>
        private string? Lift(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceType,
            ITypeSymbol destinationType,
            string destinationName)
        {
            ITypeSymbol? sourceUnderlying = TypeFacts.NullableUnderlying(sourceType);
            ITypeSymbol? destinationUnderlying = TypeFacts.NullableUnderlying(destinationType);

            if (sourceUnderlying is not null)
            {
                string? inner = Convert(
                    plan,
                    expression + ".Value",
                    sourceUnderlying,
                    destinationUnderlying ?? destinationType,
                    destinationName);

                if (inner is null)
                {
                    return null;
                }

                if (destinationUnderlying is not null)
                {
                    inner = "(" + TypeFacts.Bare(destinationType) + ")(" + inner + ")";
                }

                return "(" + expression + ".HasValue ? " + inner +
                    " : default(" + TypeFacts.Bare(destinationType) + ")!)";
            }

            if (destinationUnderlying is null)
            {
                return null;
            }

            string? value = Convert(plan, expression, sourceType, destinationUnderlying, destinationName);

            if (value is null)
            {
                return null;
            }

            string wrapped = "(" + TypeFacts.Bare(destinationType) + ")(" + value + ")";

            return sourceType.IsValueType
                ? wrapped
                : "(" + expression + " is null ? default(" + TypeFacts.Bare(destinationType) + ") : " + wrapped + ")";
        }

        private MethodPlan? Lookup(ITypeSymbol source, ITypeSymbol destination)
        {
            foreach (MethodPlan plan in plans)
            {
                if (TypeFacts.Same(plan.SourceType, source) && TypeFacts.Same(plan.DestinationType, destination))
                {
                    return plan;
                }
            }

            return null;
        }

        private void Report(DiagnosticDescriptor descriptor, MethodPlan plan, params object[] extra)
        {
            var arguments = new List<object>
            {
                TypeFacts.Display(plan.SourceType),
                TypeFacts.Display(plan.DestinationType),
            };

            arguments.AddRange(extra);

            context.ReportDiagnostic(Diagnostic.Create(
                descriptor,
                plan.Method.Locations.FirstOrDefault(),
                arguments.ToArray()));
        }

        /// <summary>
        /// The enum rules, written as code rather than carried out at run time.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The run-time engine matches enum members by name and only falls back to the number,
        /// which is what <c>EnumMappingPolicy.ByNameThenValue</c> means and what it does unless it
        /// is told otherwise. A cast is the number alone, so the two engines answer differently
        /// the first time anybody reorders an enum — and differently in the quiet way, returning
        /// another member rather than failing.
        /// </para>
        /// <para>
        /// Both enums are known here, so the correspondence is settled while the project compiles
        /// and what is emitted is a switch over constants: one case per name the two sides share,
        /// with the cast underneath for everything else, which is also where a value the source
        /// enum never declared ends up.
        /// </para>
        /// </remarks>
        private string? TryEnum(string expression, ITypeSymbol sourceType, ITypeSymbol destinationType)
        {
            bool sourceIsEnum = sourceType.TypeKind == TypeKind.Enum;
            bool destinationIsEnum = destinationType.TypeKind == TypeKind.Enum;

            if (sourceIsEnum && destinationIsEnum)
            {
                return Converter(
                    sourceType,
                    destinationType,
                    () => new EnumFromEnum(
                        ConverterName(sourceType, destinationType),
                        sourceType,
                        destinationType)) + "(" + expression + ")";
            }

            if (sourceType.SpecialType == SpecialType.System_String && destinationIsEnum)
            {
                return Converter(
                    sourceType,
                    destinationType,
                    () => new EnumFromText(
                        ConverterName(sourceType, destinationType),
                        destinationType)) + "(" + expression + ")";
            }

            if ((sourceIsEnum && IsNumeric(destinationType)) || (IsNumeric(sourceType) && destinationIsEnum))
            {
                return "(" + TypeFacts.Bare(destinationType) + ")" + expression;
            }

            return null;
        }

        private string Converter(ITypeSymbol sourceType, ITypeSymbol destinationType, Func<EnumConverter> create)
        {
            string key = TypeFacts.Bare(sourceType) + "->" + TypeFacts.Bare(destinationType);

            if (!converters.TryGetValue(key, out EnumConverter? existing))
            {
                existing = create();
                converters.Add(key, existing);
            }

            return existing.Name;
        }

        private string ConverterName(ITypeSymbol sourceType, ITypeSymbol destinationType)
        {
            string candidate = "Convert" + sourceType.Name + "To" + destinationType.Name;
            string name = candidate;

            for (int suffix = 2; Taken(name); suffix++)
            {
                name = candidate + suffix.ToString(CultureInfo.InvariantCulture);
            }

            return name;
        }

        private bool Taken(string name)
        {
            foreach (EnumConverter converter in converters.Values)
            {
                if (string.Equals(converter.Name, name, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            foreach (MethodPlan plan in plans)
            {
                if (string.Equals(plan.Method.Name, name, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsNumeric(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_SByte:
                case SpecialType.System_Byte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                    return true;

                default:
                    return false;
            }
        }

        /// <summary>Every declared member of an enum, in declaration order.</summary>
        private static List<IFieldSymbol> Members(ITypeSymbol type)
        {
            var members = new List<IFieldSymbol>();

            foreach (IFieldSymbol field in type.GetMembers().OfType<IFieldSymbol>())
            {
                if (field.HasConstantValue)
                {
                    members.Add(field);
                }
            }

            return members;
        }

        private abstract class EnumConverter
        {
            protected EnumConverter(string name)
            {
                Name = name;
            }

            internal string Name { get; }

            internal abstract void Write(StringBuilder text, string indent);
        }

        private sealed class EnumFromEnum : EnumConverter
        {
            private readonly ITypeSymbol source;
            private readonly ITypeSymbol destination;

            internal EnumFromEnum(string name, ITypeSymbol source, ITypeSymbol destination)
                : base(name)
            {
                this.source = source;
                this.destination = destination;
            }

            internal override void Write(StringBuilder text, string indent)
            {
                string sourceName = TypeFacts.Bare(source);
                string destinationName = TypeFacts.Bare(destination);

                text.Append(indent).Append("private static ").Append(destinationName).Append(' ')
                    .Append(Name).Append('(').Append(sourceName).AppendLine(" value)");
                text.Append(indent).AppendLine("{");

                List<string> shared = Shared();

                if (shared.Count > 0)
                {
                    text.Append(indent).AppendLine("    switch (value)");
                    text.Append(indent).AppendLine("    {");

                    foreach (string member in shared)
                    {
                        text.Append(indent).Append("        case ").Append(sourceName).Append('.')
                            .Append(member).AppendLine(":");
                        text.Append(indent).Append("            return ").Append(destinationName).Append('.')
                            .Append(member).AppendLine(";");
                    }

                    text.Append(indent).AppendLine("    }");
                    text.AppendLine();
                }

                text.Append(indent).Append("    return (").Append(destinationName).AppendLine(")value;");
                text.Append(indent).AppendLine("}");
                text.AppendLine();
            }

            /// <remarks>
            /// A name only counts when it is the one the destination would print for that value:
            /// the run-time engine parses the name and then checks it round-trips, so an alias on
            /// the destination side is not a match there either. Aliases on the source side are
            /// skipped for the same reason, and because two case labels cannot carry one constant.
            /// </remarks>
            private List<string> Shared()
            {
                var canonical = new Dictionary<object, string>();
                var byName = new Dictionary<string, object>(StringComparer.Ordinal);

                foreach (IFieldSymbol member in Members(destination))
                {
                    object value = member.ConstantValue!;

                    if (!canonical.ContainsKey(value))
                    {
                        canonical.Add(value, member.Name);
                    }

                    if (!byName.ContainsKey(member.Name))
                    {
                        byName.Add(member.Name, value);
                    }
                }

                var shared = new List<string>();
                var seen = new HashSet<object>();

                foreach (IFieldSymbol member in Members(source))
                {
                    if (!seen.Add(member.ConstantValue!))
                    {
                        continue;
                    }

                    if (byName.TryGetValue(member.Name, out object? matched) &&
                        string.Equals(canonical[matched!], member.Name, StringComparison.Ordinal))
                    {
                        shared.Add(member.Name);
                    }
                }

                return shared;
            }
        }

        /// <remarks>
        /// Text is read the way <c>Enum.TryParse</c> reads it: by name ignoring case, aliases
        /// included, and then as a number. Empty text is the absence of a value rather than a bad
        /// one, so it gives the default, which is what the run-time engine does with it too.
        /// </remarks>
        private sealed class EnumFromText : EnumConverter
        {
            private readonly ITypeSymbol destination;

            internal EnumFromText(string name, ITypeSymbol destination)
                : base(name)
            {
                this.destination = destination;
            }

            internal override void Write(StringBuilder text, string indent)
            {
                string destinationName = TypeFacts.Bare(destination);
                string underlying = TypeFacts.Bare(((INamedTypeSymbol)destination).EnumUnderlyingType!);

                text.Append(indent).Append("private static ").Append(destinationName).Append(' ')
                    .Append(Name).AppendLine("(string? value)");
                text.Append(indent).AppendLine("{");
                text.Append(indent).AppendLine("    if (string.IsNullOrEmpty(value))");
                text.Append(indent).AppendLine("    {");
                text.Append(indent).Append("        return default(").Append(destinationName).AppendLine(");");
                text.Append(indent).AppendLine("    }");
                text.AppendLine();

                foreach (IFieldSymbol member in Members(destination))
                {
                    text.Append(indent).Append("    if (string.Equals(value, \"").Append(member.Name)
                        .AppendLine("\", global::System.StringComparison.OrdinalIgnoreCase))");
                    text.Append(indent).AppendLine("    {");
                    text.Append(indent).Append("        return ").Append(destinationName).Append('.')
                        .Append(member.Name).AppendLine(";");
                    text.Append(indent).AppendLine("    }");
                    text.AppendLine();
                }

                text.Append(indent).Append("    return ").Append(underlying)
                    .Append(".TryParse(value, out ").Append(underlying).AppendLine(" number)");
                text.Append(indent).Append("        ? (").Append(destinationName).AppendLine(")number");
                text.Append(indent).Append("        : default(").Append(destinationName).AppendLine(");");
                text.Append(indent).AppendLine("}");
                text.AppendLine();
            }
        }

        private sealed class PathRead
        {
            internal PathRead(string expression, ITypeSymbol type)
            {
                Expression = expression;
                Type = type;
            }

            internal string Expression { get; }

            internal ITypeSymbol Type { get; }
        }
    }
}
