using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Mapperion.SourceGeneration
{
    /// <summary>
    /// Turns the mapping methods of one class into C#.
    /// </summary>
    internal sealed class MapperEmitter
    {
        private readonly SourceProductionContext context;
        private readonly Compilation compilation;
        private readonly List<MethodPlan> plans;
        /// <summary>The same ceiling the run-time engine puts on flattening by default.</summary>
        private const int MaxFlatteningDepth = 3;

        private readonly Dictionary<string, Helper> helpers =
            new Dictionary<string, Helper>(StringComparer.Ordinal);

        private INamedTypeSymbol? owner;

        internal MapperEmitter(SourceProductionContext context, Compilation compilation, List<MethodPlan> plans)
        {
            this.context = context;
            this.compilation = compilation;
            this.plans = plans;
        }

        internal string Write(INamedTypeSymbol mapper)
        {
            owner = mapper;

            var text = new StringBuilder();
            text.AppendLine("// <auto-generated/>");
            text.AppendLine("#nullable enable");
            text.AppendLine();

            bool namespaced = !mapper.ContainingNamespace.IsGlobalNamespace;

            if (namespaced)
            {
                text.Append("namespace ").AppendLine(mapper.ContainingNamespace.ToDisplayString());
                text.AppendLine("{");
            }

            string indent = namespaced ? "    " : string.Empty;

            text.Append(indent).Append("partial class ").AppendLine(mapper.Name);
            text.Append(indent).AppendLine("{");

            var methods = new StringBuilder();

            foreach (MethodPlan plan in plans)
            {
                WriteMethod(methods, plan, indent + "    ");
            }

            text.Append(methods);

            // Written last because they are discovered while the methods above are written.
            foreach (Helper helper in helpers.Values)
            {
                helper.Write(text, indent + "    ");
            }

            text.Append(indent).AppendLine("}");

            if (namespaced)
            {
                text.AppendLine("}");
            }

            return text.ToString();
        }

        private void WriteMethod(StringBuilder text, MethodPlan plan, string indent)
        {
            string parameter = plan.Method.Parameters[0].Name;

            text.Append(indent)
                .Append(Accessibility(plan.Method))
                .Append(" partial ")
                .Append(TypeFacts.Display(plan.DestinationType))
                .Append(' ')
                .Append(plan.Method.Name)
                .Append('(')
                .Append(TypeFacts.Display(plan.SourceType))
                .Append(' ')
                .Append(parameter)
                .AppendLine(")");

            text.Append(indent).AppendLine("{");

            if (TypeFacts.CanBeNull(plan.SourceType))
            {
                text.Append(indent).Append("    if (").Append(parameter).AppendLine(" is null)");
                text.Append(indent).AppendLine("    {");
                text.Append(indent).AppendLine("        return default!;");
                text.Append(indent).AppendLine("    }");
                text.AppendLine();
            }

            WriteDerivedDispatch(text, plan, parameter, indent);

            string body = BuildInstance(plan, parameter) ?? "default!";

            text.Append(indent).Append("    return ").Append(body).AppendLine(";");
            text.Append(indent).AppendLine("}");
            text.AppendLine();
        }

        /// <summary>
        /// Hands the work to a derived method when the instance turns out to be of a derived
        /// type, so mapping through a base reference still produces the right destination.
        /// </summary>
        /// <remarks>
        /// <para>
        /// This is what <c>Include</c> does in the run-time engine, and it is declared rather
        /// than inferred for the same reason it is there: a class that happens to derive from
        /// another is not a statement that mapping one should produce the other. A hierarchy is
        /// only dispatched over where somebody said so.
        /// </para>
        /// <para>
        /// Most derived first, so a hierarchy several levels deep picks the closest match rather
        /// than the first one that happens to fit.
        /// </para>
        /// </remarks>
        private void WriteDerivedDispatch(StringBuilder text, MethodPlan plan, string parameter, string indent)
        {
            var dispatched = new List<KeyValuePair<IncludedPair, MethodPlan>>();

            foreach (IncludedPair pair in plan.Included)
            {
                if (!Derives(pair.Source, plan.SourceType) || !Derives(pair.Destination, plan.DestinationType))
                {
                    Report(
                        GeneratorDiagnostics.IncludedPairIsNotDerived,
                        plan,
                        TypeFacts.Display(pair.Source),
                        TypeFacts.Display(pair.Destination));

                    continue;
                }

                MethodPlan? target = Lookup(pair.Source, pair.Destination);

                if (target is null)
                {
                    Report(
                        GeneratorDiagnostics.IncludedPairHasNoMethod,
                        plan,
                        TypeFacts.Display(pair.Source),
                        TypeFacts.Display(pair.Destination));

                    continue;
                }

                dispatched.Add(new KeyValuePair<IncludedPair, MethodPlan>(pair, target));
            }

            if (dispatched.Count == 0)
            {
                return;
            }

            dispatched.Sort(static (left, right) =>
            {
                if (TypeFacts.Same(left.Key.Source, right.Key.Source))
                {
                    return 0;
                }

                if (Derives(right.Key.Source, left.Key.Source))
                {
                    return 1;
                }

                return Derives(left.Key.Source, right.Key.Source) ? -1 : 0;
            });

            text.Append(indent).Append("    switch (").Append(parameter).AppendLine(")");
            text.Append(indent).AppendLine("    {");

            for (int i = 0; i < dispatched.Count; i++)
            {
                string name = "derived" + (i + 1).ToString(CultureInfo.InvariantCulture);

                text.Append(indent).Append("        case ").Append(TypeFacts.Bare(dispatched[i].Key.Source))
                    .Append(' ').Append(name).AppendLine(":");
                text.Append(indent).Append("            return ").Append(dispatched[i].Value.Method.Name)
                    .Append('(').Append(name).AppendLine(");");
            }

            text.Append(indent).AppendLine("    }");
            text.AppendLine();
        }

        private static bool Derives(ITypeSymbol candidate, ITypeSymbol ancestor)
        {
            for (ITypeSymbol? current = candidate; current is not null; current = current.BaseType)
            {
                if (TypeFacts.Same(current, ancestor))
                {
                    return true;
                }
            }

            return false;
        }

        private static string Accessibility(IMethodSymbol method)
        {
            switch (method.DeclaredAccessibility)
            {
                case Microsoft.CodeAnalysis.Accessibility.Public:
                    return "public";

                case Microsoft.CodeAnalysis.Accessibility.Internal:
                    return "internal";

                case Microsoft.CodeAnalysis.Accessibility.Protected:
                    return "protected";

                default:
                    return "private";
            }
        }

        private string? BuildInstance(MethodPlan plan, string parameter)
        {
            // An enum is not built, it is converted, and a map straight to one is a map the
            // run-time engine takes without comment.
            if (plan.DestinationType.TypeKind == TypeKind.Enum)
            {
                return Convert(plan, parameter, plan.SourceType, plan.DestinationType, plan.Method.Name);
            }

            ITypeSymbol? element = TypeFacts.ElementOf(plan.SourceType);
            string? materialiser = TypeFacts.Materialiser(plan.DestinationType);

            if (element is not null && materialiser is not null)
            {
                return Sequence(plan, parameter, element, materialiser, "(element)");
            }

            if (plan.DestinationType is not INamedTypeSymbol destination)
            {
                Report(GeneratorDiagnostics.CannotConstruct, plan);
                return null;
            }

            var assigned = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            string creation;

            if (TypeFacts.Parameterless(destination) is not null)
            {
                creation = "new " + TypeFacts.Bare(destination) + "()";
            }
            else
            {
                IMethodSymbol? constructor = TypeFacts.SoleConstructor(destination);

                if (constructor is null)
                {
                    Report(GeneratorDiagnostics.CannotConstruct, plan);
                    return null;
                }

                var arguments = new List<string>();

                foreach (IParameterSymbol argument in constructor.Parameters)
                {
                    string? value = Resolve(plan, parameter, argument.Name, argument.Type);

                    if (value is null)
                    {
                        return null;
                    }

                    arguments.Add(value);
                    assigned.Add(argument.Name);
                }

                creation = "new " + TypeFacts.Bare(destination) + "(" + string.Join(", ", arguments) + ")";
            }

            var initialisers = new List<string>();

            foreach (IPropertySymbol member in TypeFacts.Writable(destination))
            {
                if (assigned.Contains(member.Name))
                {
                    continue;
                }

                if (plan.Ignored.Contains(member.Name))
                {
                    continue;
                }

                string? value = Resolve(plan, parameter, member.Name, member.Type);

                if (value is null)
                {
                    return null;
                }

                initialisers.Add(member.Name + " = " + value);
            }

            return initialisers.Count == 0
                ? creation
                : creation + " { " + string.Join(", ", initialisers) + " }";
        }

        private string? Sequence(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceElement,
            string materialiser,
            string destinationName)
        {
            ITypeSymbol destinationElement = TypeFacts.ElementOf(plan.DestinationType) ?? sourceElement;
            return Sequence(plan, expression, sourceElement, destinationElement, materialiser, destinationName);
        }

        private string? Sequence(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceElement,
            ITypeSymbol destinationElement,
            string materialiser,
            string destinationName)
        {
            // A collection that is not there gives an empty one rather than throwing, which is
            // what the run-time engine does with it unless a configuration asks for null
            // collections — and that configuration cannot be seen from here.
            string projected = expression + " ?? global::System.Linq.Enumerable.Empty<" +
                TypeFacts.Bare(sourceElement) + ">()";

            if (!TypeFacts.Same(sourceElement, destinationElement))
            {
                MethodPlan? element = Lookup(sourceElement, destinationElement);

                if (element is null)
                {
                    Report(
                        GeneratorDiagnostics.NoConversion,
                        plan,
                        destinationName,
                        TypeFacts.Display(sourceElement),
                        TypeFacts.Display(destinationElement));

                    return null;
                }

                projected = "global::System.Linq.Enumerable.Select(" + projected + ", " + element.Method.Name + ")";
            }

            return "global::System.Linq.Enumerable." + materialiser + "(" + projected + ")";
        }

        private string? Resolve(MethodPlan plan, string parameter, string destinationName, ITypeSymbol destinationType)
        {
            if (plan.Ignored.Contains(destinationName))
            {
                return "default(" + TypeFacts.Bare(destinationType) + ")!";
            }

            if (plan.Resolvers.TryGetValue(destinationName, out string? resolver))
            {
                IMethodSymbol? method = Resolver(plan, resolver);

                if (method is null)
                {
                    Report(GeneratorDiagnostics.UnknownResolver, plan, resolver);
                    return null;
                }

                return Convert(
                    plan,
                    method.Name + "(" + parameter + ")",
                    method.ReturnType,
                    destinationType,
                    destinationName);
            }

            if (plan.ExplicitSources.TryGetValue(destinationName, out string? path))
            {
                PathRead? read = ReadPath(plan, parameter, path);

                return read is null
                    ? null
                    : Convert(plan, read.Expression, read.Type, destinationType, destinationName);
            }

            List<IPropertySymbol>? match = MatchPath(plan.SourceType, destinationName, 1);

            if (match is null)
            {
                Report(GeneratorDiagnostics.UnmappedMember, plan, destinationName);
                return null;
            }

            PathRead flattened = Read(parameter, plan.SourceType, match);
            return Convert(plan, flattened.Expression, flattened.Type, destinationType, destinationName);
        }

        /// <summary>
        /// The method named by <c>[MapperResolve]</c>, which is what a value resolver is once
        /// there is no container to take it out of: a method beside the mapping ones, handed the
        /// whole source.
        /// </summary>
        private IMethodSymbol? Resolver(MethodPlan plan, string name)
        {
            if (owner is null)
            {
                return null;
            }

            foreach (IMethodSymbol method in owner.GetMembers().OfType<IMethodSymbol>())
            {
                if (string.Equals(method.Name, name, StringComparison.Ordinal) &&
                    !method.ReturnsVoid &&
                    method.Parameters.Length == 1 &&
                    Derives(plan.SourceType, method.Parameters[0].Type))
                {
                    return method;
                }
            }

            return null;
        }

        /// <summary>
        /// The source path that feeds a destination member: the member of that name, and failing
        /// that the chain of members whose names spell it.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Flattening is the convention AutoMapper is known for and the run-time engine does it,
        /// so a destination called <c>CustomerAddressCity</c> finds <c>Customer.Address.City</c>
        /// without being told. Leaving it out here meant the generator reported a member as
        /// unmapped that the other engine mapped on its own, and the same configuration behaved
        /// differently depending on which engine read it.
        /// </para>
        /// <para>
        /// Three members deep, the same ceiling the run-time engine uses by default. The affixes
        /// and the naming conventions are not read: they are set on a
        /// <c>MapperConfiguration</c>, which does not exist at compile time, so what is
        /// implemented here is the default spelling on both sides.
        /// </para>
        /// </remarks>
        private static List<IPropertySymbol>? MatchPath(ITypeSymbol sourceType, string name, int depth)
        {
            IPropertySymbol? direct = Match(sourceType, name);

            if (direct is not null)
            {
                return new List<IPropertySymbol> { direct };
            }

            if (depth >= MaxFlatteningDepth)
            {
                return null;
            }

            foreach (IPropertySymbol candidate in TypeFacts.Readable(sourceType))
            {
                if (candidate.Name.Length == 0 ||
                    name.Length <= candidate.Name.Length ||
                    !name.StartsWith(candidate.Name, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                List<IPropertySymbol>? tail = MatchPath(
                    candidate.Type,
                    name.Substring(candidate.Name.Length),
                    depth + 1);

                if (tail is not null)
                {
                    tail.Insert(0, candidate);
                    return tail;
                }
            }

            return null;
        }

        private static IPropertySymbol? Match(ITypeSymbol sourceType, string name)
        {
            List<IPropertySymbol> readable = TypeFacts.Readable(sourceType);

            foreach (IPropertySymbol property in readable)
            {
                if (string.Equals(property.Name, name, StringComparison.Ordinal))
                {
                    return property;
                }
            }

            foreach (IPropertySymbol property in readable)
            {
                if (string.Equals(property.Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    return property;
                }
            }

            return null;
        }

        /// <remarks>
        /// A path guards every step that could be null, so a missing link in the chain yields the
        /// default rather than throwing. The guards re-read the intermediate members, which the run
        /// time compiler avoids by binding locals; here the readable shape of the generated code is
        /// worth more than saving a property read.
        /// </remarks>
        private PathRead? ReadPath(MethodPlan plan, string parameter, string path)
        {
            ITypeSymbol current = plan.SourceType;
            var steps = new List<IPropertySymbol>();

            foreach (string name in path.Split('.'))
            {
                IPropertySymbol? property = Match(current, name);

                if (property is null)
                {
                    Report(GeneratorDiagnostics.UnknownMember, plan, path, TypeFacts.Display(plan.SourceType));
                    return null;
                }

                steps.Add(property);
                current = property.Type;
            }

            return Read(parameter, plan.SourceType, steps);
        }

        private static PathRead Read(string parameter, ITypeSymbol sourceType, List<IPropertySymbol> steps)
        {
            ITypeSymbol current = sourceType;
            string expression = parameter;
            var guards = new List<string>();

            for (int i = 0; i < steps.Count; i++)
            {
                if (i > 0 && TypeFacts.CanBeNull(current))
                {
                    guards.Add(expression + " is not null");
                }

                expression += "." + steps[i].Name;
                current = steps[i].Type;
            }

            if (guards.Count == 0)
            {
                return new PathRead(expression, current);
            }

            string guarded = "(" + string.Join(" && ", guards) + " ? " + expression +
                " : default(" + TypeFacts.Bare(current) + ")!)";

            return new PathRead(guarded, current);
        }

        private string? Convert(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceType,
            ITypeSymbol destinationType,
            string destinationName)
        {
            // Before the check for one type, the way the run-time engine orders it: a collection
            // is copied into the destination rather than handed over, so the two objects do not
            // end up sharing a list that either of them can then change under the other.
            string? copied = TryDictionary(plan, expression, sourceType, destinationType, destinationName);

            if (copied is not null)
            {
                return copied;
            }

            ITypeSymbol? sourceElement = TypeFacts.ElementOf(sourceType);
            string? materialiser = TypeFacts.Materialiser(destinationType);

            if (sourceElement is not null && materialiser is not null)
            {
                ITypeSymbol? destinationElement = TypeFacts.ElementOf(destinationType);

                if (destinationElement is not null)
                {
                    return Sequence(plan, expression, sourceElement, destinationElement, materialiser, destinationName);
                }
            }

            if (TypeFacts.Same(sourceType, destinationType))
            {
                return expression;
            }

            string? lifted = Lift(plan, expression, sourceType, destinationType, destinationName);

            if (lifted is not null)
            {
                return lifted;
            }

            Conversion conversion = ((CSharpCompilation)compilation).ClassifyConversion(sourceType, destinationType);

            if (conversion.Exists && conversion.IsImplicit)
            {
                return expression;
            }

            // Before the declared maps, which is where the run-time engine looks at them too. A
            // pair of enums is a conversion and not a map, and putting it the other way round
            // makes a method declared for that pair call itself.
            string? asEnum = TryEnum(expression, sourceType, destinationType);

            if (asEnum is not null)
            {
                return asEnum;
            }

            if (conversion.Exists && (conversion.IsNumeric || conversion.IsEnumeration))
            {
                return "(" + TypeFacts.Bare(destinationType) + ")" + expression;
            }

            if (destinationType.SpecialType == SpecialType.System_String)
            {
                return TypeFacts.CanBeNull(sourceType)
                    ? expression + "?.ToString()"
                    : expression + ".ToString()";
            }

            MethodPlan? mapping = Lookup(sourceType, destinationType);

            if (mapping is not null)
            {
                return mapping.Method.Name + "(" + expression + ")";
            }

            string? read = TryParseText(expression, sourceType, destinationType)
                ?? TryChangeType(expression, sourceType, destinationType);

            if (read is not null)
            {
                return read;
            }

            Report(
                GeneratorDiagnostics.NoConversion,
                plan,
                destinationName,
                TypeFacts.Display(sourceType),
                TypeFacts.Display(destinationType));

            return null;
        }

        /// <summary>
        /// Lifts a conversion over a nullable on either side.
        /// </summary>
        /// <remarks>
        /// The run-time engine settles this before it looks at anything else about the pair, so an
        /// absent value gives the destination's default instead of reaching a conversion that
        /// would throw on it. Answering it in the same place is what keeps the two engines saying
        /// the same thing about a value that is not there.
        /// </remarks>
        private string? Lift(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceType,
            ITypeSymbol destinationType,
            string destinationName)
        {
            ITypeSymbol? sourceUnderlying = TypeFacts.NullableUnderlying(sourceType);
            ITypeSymbol? destinationUnderlying = TypeFacts.NullableUnderlying(destinationType);

            if (sourceUnderlying is not null)
            {
                string? inner = Convert(
                    plan,
                    expression + ".Value",
                    sourceUnderlying,
                    destinationUnderlying ?? destinationType,
                    destinationName);

                if (inner is null)
                {
                    return null;
                }

                if (destinationUnderlying is not null)
                {
                    inner = "(" + TypeFacts.Bare(destinationType) + ")(" + inner + ")";
                }

                return "(" + expression + ".HasValue ? " + inner +
                    " : default(" + TypeFacts.Bare(destinationType) + ")!)";
            }

            if (destinationUnderlying is null)
            {
                return null;
            }

            string? value = Convert(plan, expression, sourceType, destinationUnderlying, destinationName);

            if (value is null)
            {
                return null;
            }

            string wrapped = "(" + TypeFacts.Bare(destinationType) + ")(" + value + ")";

            return sourceType.IsValueType
                ? wrapped
                : "(" + expression + " is null ? default(" + TypeFacts.Bare(destinationType) + ") : " + wrapped + ")";
        }

        private MethodPlan? Lookup(ITypeSymbol source, ITypeSymbol destination)
        {
            foreach (MethodPlan plan in plans)
            {
                if (TypeFacts.Same(plan.SourceType, source) && TypeFacts.Same(plan.DestinationType, destination))
                {
                    return plan;
                }
            }

            return null;
        }

        private void Report(DiagnosticDescriptor descriptor, MethodPlan plan, params object[] extra)
        {
            var arguments = new List<object>
            {
                TypeFacts.Display(plan.SourceType),
                TypeFacts.Display(plan.DestinationType),
            };

            arguments.AddRange(extra);

            context.ReportDiagnostic(Diagnostic.Create(
                descriptor,
                plan.Method.Locations.FirstOrDefault(),
                arguments.ToArray()));
        }

        /// <summary>
        /// The enum rules, written as code rather than carried out at run time.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The run-time engine matches enum members by name and only falls back to the number,
        /// which is what <c>EnumMappingPolicy.ByNameThenValue</c> means and what it does unless it
        /// is told otherwise. A cast is the number alone, so the two engines answer differently
        /// the first time anybody reorders an enum — and differently in the quiet way, returning
        /// another member rather than failing.
        /// </para>
        /// <para>
        /// Both enums are known here, so the correspondence is settled while the project compiles
        /// and what is emitted is a switch over constants: one case per name the two sides share,
        /// with the cast underneath for everything else, which is also where a value the source
        /// enum never declared ends up.
        /// </para>
        /// </remarks>
        private string? TryEnum(string expression, ITypeSymbol sourceType, ITypeSymbol destinationType)
        {
            bool sourceIsEnum = sourceType.TypeKind == TypeKind.Enum;
            bool destinationIsEnum = destinationType.TypeKind == TypeKind.Enum;

            if (sourceIsEnum && destinationIsEnum)
            {
                return Named(
                    sourceType,
                    destinationType,
                    () => new EnumFromEnum(
                        ConverterName(sourceType, destinationType),
                        sourceType,
                        destinationType)) + "(" + expression + ")";
            }

            if (sourceType.SpecialType == SpecialType.System_String && destinationIsEnum)
            {
                return Named(
                    sourceType,
                    destinationType,
                    () => new EnumFromText(
                        ConverterName(sourceType, destinationType),
                        destinationType)) + "(" + expression + ")";
            }

            if ((sourceIsEnum && IsNumeric(destinationType)) || (IsNumeric(sourceType) && destinationIsEnum))
            {
                return "(" + TypeFacts.Bare(destinationType) + ")" + expression;
            }

            return null;
        }

        /// <summary>
        /// Copies a dictionary into a dictionary, converting the keys and the values.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The run-time engine has done this from the start and the generator had nothing for it,
        /// so a member the other engine copied was reported here as having no conversion. Written
        /// out as a loop rather than as <c>ToDictionary</c>, because the two do not agree about a
        /// repeated key: the engine's last entry wins, and <c>ToDictionary</c> throws.
        /// </para>
        /// <para>
        /// A source that is not there gives an empty dictionary rather than nothing, which is
        /// what the other engine does with it unless a configuration asks for null collections —
        /// and that configuration is not visible from here.
        /// </para>
        /// </remarks>
        private string? TryDictionary(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceType,
            ITypeSymbol destinationType,
            string destinationName)
        {
            if (!TypeFacts.IsDictionary(sourceType, out ITypeSymbol? sourceKey, out ITypeSymbol? sourceValue) ||
                !TypeFacts.IsDestinationDictionary(
                    destinationType,
                    out ITypeSymbol? destinationKey,
                    out ITypeSymbol? destinationValue))
            {
                return null;
            }

            string? key = Convert(plan, "entry.Key", sourceKey!, destinationKey!, destinationName);
            string? value = Convert(plan, "entry.Value", sourceValue!, destinationValue!, destinationName);

            if (key is null || value is null)
            {
                return null;
            }

            return Named(
                sourceType,
                destinationType,
                () => new DictionaryCopy(
                    ConverterName(sourceType, destinationType),
                    sourceType,
                    sourceKey!,
                    sourceValue!,
                    destinationKey!,
                    destinationValue!,
                    key,
                    value)) + "(" + expression + ")";
        }

        /// <summary>
        /// Reads a value out of text for the three types that are not <c>IConvertible</c>.
        /// </summary>
        /// <remarks>
        /// <c>Guid</c>, <c>DateOnly</c> and <c>TimeOnly</c> arrived in the run-time engine in
        /// 0.11.0 and never arrived here, so an identifier or a date coming out of a column
        /// somebody typed as <c>varchar</c> mapped on one engine and stopped the build on the
        /// other. Empty text is the absence of a value rather than a bad one and gives the
        /// default, and the invariant culture is used, both to match the engine.
        /// </remarks>
        private string? TryParseText(string expression, ITypeSymbol sourceType, ITypeSymbol destinationType)
        {
            if (sourceType.SpecialType != SpecialType.System_String)
            {
                return null;
            }

            string name = TypeFacts.Bare(destinationType);

            if (name is not ("global::System.Guid" or "global::System.DateOnly" or "global::System.TimeOnly"))
            {
                return null;
            }

            bool cultured = name != "global::System.Guid";

            return Named(
                sourceType,
                destinationType,
                () => new TextParse(
                    ConverterName(sourceType, destinationType),
                    destinationType,
                    cultured)) + "(" + expression + ")";
        }

        /// <summary>
        /// The last thing the run-time engine tries: two types that both say they can convert
        /// themselves, handed to <c>Convert.ChangeType</c> with the invariant culture.
        /// </summary>
        private string? TryChangeType(string expression, ITypeSymbol sourceType, ITypeSymbol destinationType)
        {
            if (!IsConvertible(sourceType) || !IsConvertible(destinationType))
            {
                return null;
            }

            return Named(
                sourceType,
                destinationType,
                () => new ConvertibleChange(
                    ConverterName(sourceType, destinationType),
                    sourceType,
                    destinationType)) + "(" + expression + ")";
        }

        private static bool IsConvertible(ITypeSymbol type)
        {
            foreach (INamedTypeSymbol contract in type.AllInterfaces)
            {
                if (contract.Name == "IConvertible" && contract.ContainingNamespace.ToDisplayString() == "System")
                {
                    return true;
                }
            }

            return false;
        }

        private string Named(ITypeSymbol sourceType, ITypeSymbol destinationType, Func<Helper> create)
        {
            string key = TypeFacts.Bare(sourceType) + "->" + TypeFacts.Bare(destinationType);

            if (!helpers.TryGetValue(key, out Helper? existing))
            {
                existing = create();
                helpers.Add(key, existing);
            }

            return existing.Name;
        }

        private string ConverterName(ITypeSymbol sourceType, ITypeSymbol destinationType)
        {
            string candidate = "Convert" + sourceType.Name + "To" + destinationType.Name;
            string name = candidate;

            for (int suffix = 2; Taken(name); suffix++)
            {
                name = candidate + suffix.ToString(CultureInfo.InvariantCulture);
            }

            return name;
        }

        private bool Taken(string name)
        {
            foreach (Helper helper in helpers.Values)
            {
                if (string.Equals(helper.Name, name, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            foreach (MethodPlan plan in plans)
            {
                if (string.Equals(plan.Method.Name, name, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsNumeric(ITypeSymbol type)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_SByte:
                case SpecialType.System_Byte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                    return true;

                default:
                    return false;
            }
        }

        /// <summary>Every declared member of an enum, in declaration order.</summary>
        private static List<IFieldSymbol> Members(ITypeSymbol type)
        {
            var members = new List<IFieldSymbol>();

            foreach (IFieldSymbol field in type.GetMembers().OfType<IFieldSymbol>())
            {
                if (field.HasConstantValue)
                {
                    members.Add(field);
                }
            }

            return members;
        }

        private abstract class Helper
        {
            protected Helper(string name)
            {
                Name = name;
            }

            internal string Name { get; }

            internal abstract void Write(StringBuilder text, string indent);
        }

        private sealed class EnumFromEnum : Helper
        {
            private readonly ITypeSymbol source;
            private readonly ITypeSymbol destination;

            internal EnumFromEnum(string name, ITypeSymbol source, ITypeSymbol destination)
                : base(name)
            {
                this.source = source;
                this.destination = destination;
            }

            internal override void Write(StringBuilder text, string indent)
            {
                string sourceName = TypeFacts.Bare(source);
                string destinationName = TypeFacts.Bare(destination);

                text.Append(indent).Append("private static ").Append(destinationName).Append(' ')
                    .Append(Name).Append('(').Append(sourceName).AppendLine(" value)");
                text.Append(indent).AppendLine("{");

                List<string> shared = Shared();

                if (shared.Count > 0)
                {
                    text.Append(indent).AppendLine("    switch (value)");
                    text.Append(indent).AppendLine("    {");

                    foreach (string member in shared)
                    {
                        text.Append(indent).Append("        case ").Append(sourceName).Append('.')
                            .Append(member).AppendLine(":");
                        text.Append(indent).Append("            return ").Append(destinationName).Append('.')
                            .Append(member).AppendLine(";");
                    }

                    text.Append(indent).AppendLine("    }");
                    text.AppendLine();
                }

                text.Append(indent).Append("    return (").Append(destinationName).AppendLine(")value;");
                text.Append(indent).AppendLine("}");
                text.AppendLine();
            }

            /// <remarks>
            /// A name only counts when it is the one the destination would print for that value:
            /// the run-time engine parses the name and then checks it round-trips, so an alias on
            /// the destination side is not a match there either. Aliases on the source side are
            /// skipped for the same reason, and because two case labels cannot carry one constant.
            /// </remarks>
            private List<string> Shared()
            {
                var canonical = new Dictionary<object, string>();
                var byName = new Dictionary<string, object>(StringComparer.Ordinal);

                foreach (IFieldSymbol member in Members(destination))
                {
                    object value = member.ConstantValue!;

                    if (!canonical.ContainsKey(value))
                    {
                        canonical.Add(value, member.Name);
                    }

                    if (!byName.ContainsKey(member.Name))
                    {
                        byName.Add(member.Name, value);
                    }
                }

                var shared = new List<string>();
                var seen = new HashSet<object>();

                foreach (IFieldSymbol member in Members(source))
                {
                    if (!seen.Add(member.ConstantValue!))
                    {
                        continue;
                    }

                    if (byName.TryGetValue(member.Name, out object? matched) &&
                        string.Equals(canonical[matched!], member.Name, StringComparison.Ordinal))
                    {
                        shared.Add(member.Name);
                    }
                }

                return shared;
            }
        }

        /// <remarks>
        /// Text is read the way <c>Enum.TryParse</c> reads it: by name ignoring case, aliases
        /// included, and then as a number. Empty text is the absence of a value rather than a bad
        /// one, so it gives the default, which is what the run-time engine does with it too.
        /// </remarks>
        private sealed class EnumFromText : Helper
        {
            private readonly ITypeSymbol destination;

            internal EnumFromText(string name, ITypeSymbol destination)
                : base(name)
            {
                this.destination = destination;
            }

            internal override void Write(StringBuilder text, string indent)
            {
                string destinationName = TypeFacts.Bare(destination);
                string underlying = TypeFacts.Bare(((INamedTypeSymbol)destination).EnumUnderlyingType!);

                text.Append(indent).Append("private static ").Append(destinationName).Append(' ')
                    .Append(Name).AppendLine("(string? value)");
                text.Append(indent).AppendLine("{");
                text.Append(indent).AppendLine("    if (string.IsNullOrEmpty(value))");
                text.Append(indent).AppendLine("    {");
                text.Append(indent).Append("        return default(").Append(destinationName).AppendLine(");");
                text.Append(indent).AppendLine("    }");
                text.AppendLine();

                foreach (IFieldSymbol member in Members(destination))
                {
                    text.Append(indent).Append("    if (string.Equals(value, \"").Append(member.Name)
                        .AppendLine("\", global::System.StringComparison.OrdinalIgnoreCase))");
                    text.Append(indent).AppendLine("    {");
                    text.Append(indent).Append("        return ").Append(destinationName).Append('.')
                        .Append(member.Name).AppendLine(";");
                    text.Append(indent).AppendLine("    }");
                    text.AppendLine();
                }

                text.Append(indent).Append("    return ").Append(underlying)
                    .Append(".TryParse(value, out ").Append(underlying).AppendLine(" number)");
                text.Append(indent).Append("        ? (").Append(destinationName).AppendLine(")number");
                text.Append(indent).Append("        : default(").Append(destinationName).AppendLine(");");
                text.Append(indent).AppendLine("}");
                text.AppendLine();
            }
        }

        private sealed class TextParse : Helper
        {
            private readonly ITypeSymbol destination;
            private readonly bool cultured;

            internal TextParse(string name, ITypeSymbol destination, bool cultured)
                : base(name)
            {
                this.destination = destination;
                this.cultured = cultured;
            }

            internal override void Write(StringBuilder text, string indent)
            {
                string name = TypeFacts.Bare(destination);
                string culture = cultured
                    ? ", global::System.Globalization.CultureInfo.InvariantCulture, " +
                      "global::System.Globalization.DateTimeStyles.None"
                    : string.Empty;

                text.Append(indent).Append("private static ").Append(name).Append(' ').Append(Name)
                    .AppendLine("(string? value)");
                text.Append(indent).AppendLine("{");
                text.Append(indent).AppendLine("    if (string.IsNullOrEmpty(value))");
                text.Append(indent).AppendLine("    {");
                text.Append(indent).Append("        return default(").Append(name).AppendLine(");");
                text.Append(indent).AppendLine("    }");
                text.AppendLine();
                text.Append(indent).Append("    if (").Append(name).Append(".TryParse(value").Append(culture)
                    .Append(", out ").Append(name).AppendLine(" parsed))");
                text.Append(indent).AppendLine("    {");
                text.Append(indent).AppendLine("        return parsed;");
                text.Append(indent).AppendLine("    }");
                text.AppendLine();
                text.Append(indent).Append("    throw new global::System.FormatException(\"'\" + value + \"' is not a ")
                    .Append(destination.Name)
                    .AppendLine(". Text is read with the invariant culture; map the member from an expression to read it another way.\");");
                text.Append(indent).AppendLine("}");
                text.AppendLine();
            }
        }

        private sealed class ConvertibleChange : Helper
        {
            private readonly ITypeSymbol source;
            private readonly ITypeSymbol destination;

            internal ConvertibleChange(string name, ITypeSymbol source, ITypeSymbol destination)
                : base(name)
            {
                this.source = source;
                this.destination = destination;
            }

            internal override void Write(StringBuilder text, string indent)
            {
                string name = TypeFacts.Bare(destination);
                bool nullable = TypeFacts.CanBeNull(source);

                text.Append(indent).Append("private static ").Append(name).Append(' ').Append(Name)
                    .Append('(').Append(TypeFacts.Bare(source)).Append(nullable ? "? " : " ")
                    .AppendLine("value)");
                text.Append(indent).AppendLine("{");

                if (nullable)
                {
                    text.Append(indent).AppendLine("    if (value is null)");
                    text.Append(indent).AppendLine("    {");
                    text.Append(indent).Append("        return default(").Append(name).AppendLine(");");
                    text.Append(indent).AppendLine("    }");
                    text.AppendLine();
                }

                text.Append(indent).Append("    return (").Append(name)
                    .Append(")global::System.Convert.ChangeType(value, typeof(").Append(name)
                    .AppendLine("), global::System.Globalization.CultureInfo.InvariantCulture);");
                text.Append(indent).AppendLine("}");
                text.AppendLine();
            }
        }

        private sealed class DictionaryCopy : Helper
        {
            private readonly ITypeSymbol source;
            private readonly ITypeSymbol sourceKey;
            private readonly ITypeSymbol sourceValue;
            private readonly ITypeSymbol destinationKey;
            private readonly ITypeSymbol destinationValue;
            private readonly string key;
            private readonly string value;

            internal DictionaryCopy(
                string name,
                ITypeSymbol source,
                ITypeSymbol sourceKey,
                ITypeSymbol sourceValue,
                ITypeSymbol destinationKey,
                ITypeSymbol destinationValue,
                string key,
                string value)
                : base(name)
            {
                this.source = source;
                this.sourceKey = sourceKey;
                this.sourceValue = sourceValue;
                this.destinationKey = destinationKey;
                this.destinationValue = destinationValue;
                this.key = key;
                this.value = value;
            }

            internal override void Write(StringBuilder text, string indent)
            {
                string entry = "global::System.Collections.Generic.KeyValuePair<" +
                    TypeFacts.Bare(sourceKey) + ", " + TypeFacts.Bare(sourceValue) + ">";
                string built = "global::System.Collections.Generic.Dictionary<" +
                    TypeFacts.Bare(destinationKey) + ", " + TypeFacts.Bare(destinationValue) + ">";
                bool nullable = TypeFacts.CanBeNull(source);

                // Not static: the value conversion can be a call to one of the mapping methods,
                // and those are instance methods on the class this is written into.
                text.Append(indent).Append("private ").Append(built).Append(' ').Append(Name)
                    .Append('(').Append(TypeFacts.Bare(source)).Append(nullable ? "? " : " ")
                    .AppendLine("source)");
                text.Append(indent).AppendLine("{");
                text.Append(indent).Append("    ").Append(built).Append(" result = new ").Append(built)
                    .AppendLine("();");
                text.AppendLine();

                if (nullable)
                {
                    text.Append(indent).AppendLine("    if (source is null)");
                    text.Append(indent).AppendLine("    {");
                    text.Append(indent).AppendLine("        return result;");
                    text.Append(indent).AppendLine("    }");
                    text.AppendLine();
                }

                text.Append(indent).Append("    foreach (").Append(entry).Append(" entry in (")
                    .Append("global::System.Collections.Generic.IEnumerable<").Append(entry)
                    .AppendLine(">)source)");
                text.Append(indent).AppendLine("    {");
                text.Append(indent).Append("        result[").Append(key).Append("] = ").Append(value)
                    .AppendLine(";");
                text.Append(indent).AppendLine("    }");
                text.AppendLine();
                text.Append(indent).AppendLine("    return result;");
                text.Append(indent).AppendLine("}");
                text.AppendLine();
            }
        }

        private sealed class PathRead
        {
            internal PathRead(string expression, ITypeSymbol type)
            {
                Expression = expression;
                Type = type;
            }

            internal string Expression { get; }

            internal ITypeSymbol Type { get; }
        }
    }
}
