using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Mapperion.SourceGeneration
{
    /// <summary>
    /// Turns the mapping methods of one class into C#.
    /// </summary>
    internal sealed class MapperEmitter
    {
        private readonly SourceProductionContext context;
        private readonly Compilation compilation;
        private readonly List<MethodPlan> plans;

        internal MapperEmitter(SourceProductionContext context, Compilation compilation, List<MethodPlan> plans)
        {
            this.context = context;
            this.compilation = compilation;
            this.plans = plans;
        }

        internal string Write(INamedTypeSymbol mapper)
        {
            var text = new StringBuilder();
            text.AppendLine("// <auto-generated/>");
            text.AppendLine("#nullable enable");
            text.AppendLine();

            bool namespaced = !mapper.ContainingNamespace.IsGlobalNamespace;

            if (namespaced)
            {
                text.Append("namespace ").AppendLine(mapper.ContainingNamespace.ToDisplayString());
                text.AppendLine("{");
            }

            string indent = namespaced ? "    " : string.Empty;

            text.Append(indent).Append("partial class ").AppendLine(mapper.Name);
            text.Append(indent).AppendLine("{");

            foreach (MethodPlan plan in plans)
            {
                WriteMethod(text, plan, indent + "    ");
            }

            text.Append(indent).AppendLine("}");

            if (namespaced)
            {
                text.AppendLine("}");
            }

            return text.ToString();
        }

        private void WriteMethod(StringBuilder text, MethodPlan plan, string indent)
        {
            string parameter = plan.Method.Parameters[0].Name;

            text.Append(indent)
                .Append(Accessibility(plan.Method))
                .Append(" partial ")
                .Append(TypeFacts.Display(plan.DestinationType))
                .Append(' ')
                .Append(plan.Method.Name)
                .Append('(')
                .Append(TypeFacts.Display(plan.SourceType))
                .Append(' ')
                .Append(parameter)
                .AppendLine(")");

            text.Append(indent).AppendLine("{");

            if (TypeFacts.CanBeNull(plan.SourceType))
            {
                text.Append(indent).Append("    if (").Append(parameter).AppendLine(" is null)");
                text.Append(indent).AppendLine("    {");
                text.Append(indent).AppendLine("        return default!;");
                text.Append(indent).AppendLine("    }");
                text.AppendLine();
            }

            string body = BuildInstance(plan, parameter) ?? "default!";

            text.Append(indent).Append("    return ").Append(body).AppendLine(";");
            text.Append(indent).AppendLine("}");
            text.AppendLine();
        }

        private static string Accessibility(IMethodSymbol method)
        {
            switch (method.DeclaredAccessibility)
            {
                case Microsoft.CodeAnalysis.Accessibility.Public:
                    return "public";

                case Microsoft.CodeAnalysis.Accessibility.Internal:
                    return "internal";

                case Microsoft.CodeAnalysis.Accessibility.Protected:
                    return "protected";

                default:
                    return "private";
            }
        }

        private string? BuildInstance(MethodPlan plan, string parameter)
        {
            ITypeSymbol? element = TypeFacts.ElementOf(plan.SourceType);
            string? materialiser = TypeFacts.Materialiser(plan.DestinationType);

            if (element is not null && materialiser is not null)
            {
                return Sequence(plan, parameter, element, materialiser, "(element)");
            }

            if (plan.DestinationType is not INamedTypeSymbol destination)
            {
                Report(GeneratorDiagnostics.CannotConstruct, plan);
                return null;
            }

            var assigned = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            string creation;

            if (TypeFacts.Parameterless(destination) is not null)
            {
                creation = "new " + TypeFacts.Bare(destination) + "()";
            }
            else
            {
                IMethodSymbol? constructor = TypeFacts.SoleConstructor(destination);

                if (constructor is null)
                {
                    Report(GeneratorDiagnostics.CannotConstruct, plan);
                    return null;
                }

                var arguments = new List<string>();

                foreach (IParameterSymbol argument in constructor.Parameters)
                {
                    string? value = Resolve(plan, parameter, argument.Name, argument.Type);

                    if (value is null)
                    {
                        return null;
                    }

                    arguments.Add(value);
                    assigned.Add(argument.Name);
                }

                creation = "new " + TypeFacts.Bare(destination) + "(" + string.Join(", ", arguments) + ")";
            }

            var initialisers = new List<string>();

            foreach (IPropertySymbol member in TypeFacts.Writable(destination))
            {
                if (assigned.Contains(member.Name))
                {
                    continue;
                }

                if (plan.Ignored.Contains(member.Name))
                {
                    continue;
                }

                string? value = Resolve(plan, parameter, member.Name, member.Type);

                if (value is null)
                {
                    return null;
                }

                initialisers.Add(member.Name + " = " + value);
            }

            return initialisers.Count == 0
                ? creation
                : creation + " { " + string.Join(", ", initialisers) + " }";
        }

        private string? Sequence(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceElement,
            string materialiser,
            string destinationName)
        {
            ITypeSymbol destinationElement = TypeFacts.ElementOf(plan.DestinationType) ?? sourceElement;
            return Sequence(plan, expression, sourceElement, destinationElement, materialiser, destinationName);
        }

        private string? Sequence(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceElement,
            ITypeSymbol destinationElement,
            string materialiser,
            string destinationName)
        {
            string projected = expression;

            if (!TypeFacts.Same(sourceElement, destinationElement))
            {
                MethodPlan? element = Lookup(sourceElement, destinationElement);

                if (element is null)
                {
                    Report(
                        GeneratorDiagnostics.NoConversion,
                        plan,
                        destinationName,
                        TypeFacts.Display(sourceElement),
                        TypeFacts.Display(destinationElement));

                    return null;
                }

                projected = "global::System.Linq.Enumerable.Select(" + expression + ", " + element.Method.Name + ")";
            }

            return "global::System.Linq.Enumerable." + materialiser + "(" + projected + ")";
        }

        private string? Resolve(MethodPlan plan, string parameter, string destinationName, ITypeSymbol destinationType)
        {
            if (plan.Ignored.Contains(destinationName))
            {
                return "default(" + TypeFacts.Bare(destinationType) + ")!";
            }

            if (plan.ExplicitSources.TryGetValue(destinationName, out string? path))
            {
                PathRead? read = ReadPath(plan, parameter, path);

                return read is null
                    ? null
                    : Convert(plan, read.Expression, read.Type, destinationType, destinationName);
            }

            IPropertySymbol? match = Match(plan.SourceType, destinationName);

            if (match is null)
            {
                Report(GeneratorDiagnostics.UnmappedMember, plan, destinationName);
                return null;
            }

            return Convert(plan, parameter + "." + match.Name, match.Type, destinationType, destinationName);
        }

        private static IPropertySymbol? Match(ITypeSymbol sourceType, string name)
        {
            List<IPropertySymbol> readable = TypeFacts.Readable(sourceType);

            foreach (IPropertySymbol property in readable)
            {
                if (string.Equals(property.Name, name, StringComparison.Ordinal))
                {
                    return property;
                }
            }

            foreach (IPropertySymbol property in readable)
            {
                if (string.Equals(property.Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    return property;
                }
            }

            return null;
        }

        /// <remarks>
        /// A path guards every step that could be null, so a missing link in the chain yields the
        /// default rather than throwing. The guards re-read the intermediate members, which the run
        /// time compiler avoids by binding locals; here the readable shape of the generated code is
        /// worth more than saving a property read.
        /// </remarks>
        private PathRead? ReadPath(MethodPlan plan, string parameter, string path)
        {
            ITypeSymbol current = plan.SourceType;
            string expression = parameter;
            var guards = new List<string>();

            string[] steps = path.Split('.');

            for (int i = 0; i < steps.Length; i++)
            {
                IPropertySymbol? property = Match(current, steps[i]);

                if (property is null)
                {
                    Report(GeneratorDiagnostics.UnknownMember, plan, path, TypeFacts.Display(plan.SourceType));
                    return null;
                }

                if (i > 0 && TypeFacts.CanBeNull(current))
                {
                    guards.Add(expression + " is not null");
                }

                expression += "." + property.Name;
                current = property.Type;
            }

            if (guards.Count == 0)
            {
                return new PathRead(expression, current);
            }

            string guarded = "(" + string.Join(" && ", guards) + " ? " + expression +
                " : default(" + TypeFacts.Bare(current) + ")!)";

            return new PathRead(guarded, current);
        }

        private string? Convert(
            MethodPlan plan,
            string expression,
            ITypeSymbol sourceType,
            ITypeSymbol destinationType,
            string destinationName)
        {
            if (TypeFacts.Same(sourceType, destinationType))
            {
                return expression;
            }

            ITypeSymbol? sourceElement = TypeFacts.ElementOf(sourceType);
            string? materialiser = TypeFacts.Materialiser(destinationType);

            if (sourceElement is not null && materialiser is not null)
            {
                ITypeSymbol? destinationElement = TypeFacts.ElementOf(destinationType);

                if (destinationElement is not null)
                {
                    return Sequence(plan, expression, sourceElement, destinationElement, materialiser, destinationName);
                }
            }

            MethodPlan? mapping = Lookup(sourceType, destinationType);

            if (mapping is not null)
            {
                return mapping.Method.Name + "(" + expression + ")";
            }

            ITypeSymbol? underlying = TypeFacts.NullableUnderlying(sourceType);

            if (underlying is not null && TypeFacts.Same(underlying, destinationType))
            {
                return expression + ".GetValueOrDefault()";
            }

            Conversion conversion = ((CSharpCompilation)compilation).ClassifyConversion(sourceType, destinationType);

            if (conversion.Exists && conversion.IsImplicit)
            {
                return expression;
            }

            if (destinationType.SpecialType == SpecialType.System_String)
            {
                return TypeFacts.CanBeNull(sourceType)
                    ? expression + "?.ToString()"
                    : expression + ".ToString()";
            }

            if (conversion.Exists && (conversion.IsNumeric || conversion.IsEnumeration))
            {
                return "(" + TypeFacts.Bare(destinationType) + ")" + expression;
            }

            Report(
                GeneratorDiagnostics.NoConversion,
                plan,
                destinationName,
                TypeFacts.Display(sourceType),
                TypeFacts.Display(destinationType));

            return null;
        }

        private MethodPlan? Lookup(ITypeSymbol source, ITypeSymbol destination)
        {
            foreach (MethodPlan plan in plans)
            {
                if (TypeFacts.Same(plan.SourceType, source) && TypeFacts.Same(plan.DestinationType, destination))
                {
                    return plan;
                }
            }

            return null;
        }

        private void Report(DiagnosticDescriptor descriptor, MethodPlan plan, params object[] extra)
        {
            var arguments = new List<object>
            {
                TypeFacts.Display(plan.SourceType),
                TypeFacts.Display(plan.DestinationType),
            };

            arguments.AddRange(extra);

            context.ReportDiagnostic(Diagnostic.Create(
                descriptor,
                plan.Method.Locations.FirstOrDefault(),
                arguments.ToArray()));
        }

        private sealed class PathRead
        {
            internal PathRead(string expression, ITypeSymbol type)
            {
                Expression = expression;
                Type = type;
            }

            internal string Expression { get; }

            internal ITypeSymbol Type { get; }
        }
    }
}
