namespace Mapperion.SourceGeneration
{
    /// <summary>
    /// The attributes the generator adds to every compilation that uses it. They are emitted rather
    /// than shipped in a package so the generator carries no run-time dependency, and they are
    /// internal so two assemblies using the generator never collide.
    /// </summary>
    internal static class MapperAttributes
    {
        internal const string MapperAttributeName = "Mapperion.MapperAttribute";

        internal const string MapPropertyAttributeName = "Mapperion.MapPropertyAttribute";

        internal const string MapperIgnoreAttributeName = "Mapperion.MapperIgnoreAttribute";

        internal const string Source = @"// <auto-generated/>
#nullable enable

namespace Mapperion
{
    /// <summary>Marks a partial class whose partial mapping methods the generator writes.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class MapperAttribute : global::System.Attribute
    {
    }

    /// <summary>Points a destination member at a source member, by name or by a dotted path.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class MapPropertyAttribute : global::System.Attribute
    {
        public MapPropertyAttribute(string source, string destination)
        {
            Source = source;
            Destination = destination;
        }

        public string Source { get; }

        public string Destination { get; }
    }

    /// <summary>Leaves a destination member unmapped.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class MapperIgnoreAttribute : global::System.Attribute
    {
        public MapperIgnoreAttribute(string destination)
        {
            Destination = destination;
        }

        public string Destination { get; }
    }
}
";
    }
}
